# Generated by Django 3.1 on 2020-09-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название')),
                ('typeof', models.CharField(choices=[('str', 'Строка'), ('int', 'Целое число'), ('float', 'Число с плавающей точкой')], max_length=16, verbose_name='Тип аттрибута')),
                ('is_predefined', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Предопределенный атрибут?')),
            ],
            options={
                'verbose_name': 'Аттрибут объекта игры',
                'verbose_name_plural': 'Аттрибуты объекта игры',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Game_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игра и объект',
                'verbose_name_plural': 'Игры и объекты',
                'ordering': ['game', 'object'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название')),
                ('plural_name', models.CharField(max_length=128, verbose_name='Множ. число')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Активен?')),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.game_object', verbose_name='Объект игры')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'moderator'), (2, 'user'), (3, 'seller')], unique=True, verbose_name='Роль')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accstore_app.permission', verbose_name='Разрешения')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('abstractchat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accstore_app.abstractchat')),
            ],
            bases=('accstore_app.abstractchat',),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=64, null=True, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.attribute', verbose_name='Аттрибут')),
                ('product_nonprevalue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accstore_app.product', verbose_name='Продукт (для непредопределённого значения)')),
            ],
            options={
                'verbose_name': 'Значение аттрибута объекта игры',
                'verbose_name_plural': 'Значения аттрибута объекта игры',
                'unique_together': {('attribute', 'value', 'product_nonprevalue')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('sha_password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, unique=True, verbose_name='Key')),
                ('expired', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Product_PreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.value', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Товар_Значение',
                'verbose_name_plural': 'Товары_Значения',
                'unique_together': {('product', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pre_values',
            field=models.ManyToManyField(through='accstore_app.Product_PreValue', to='accstore_app.Value', verbose_name='Значения'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.seller', verbose_name='Продавец'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'active'), (1, 'done'), (2, 'in_dispute')], max_length=32, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Текст')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='game_object',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.object', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='game',
            name='g_objects',
            field=models.ManyToManyField(through='accstore_app.Game_Object', to='accstore_app.Object', verbose_name='Объекты'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'opened'), (1, 'closed')], max_length=32, verbose_name='Статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='game_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accstore_app.game_object', verbose_name='Объект игры'),
        ),
        migrations.AddField(
            model_name='abstractchat',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accstore_app.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='abstractchat',
            name='users',
            field=models.ManyToManyField(to='accstore_app.User'),
        ),
        migrations.CreateModel(
            name='ModeredPersonalChat',
            fields=[
                ('abstractchat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accstore_app.abstractchat')),
                ('moderators', models.ManyToManyField(to='accstore_app.User')),
            ],
            bases=('accstore_app.abstractchat',),
        ),
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('abstractchat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accstore_app.abstractchat')),
                ('moderators', models.ManyToManyField(to='accstore_app.User')),
            ],
            bases=('accstore_app.abstractchat',),
        ),
        migrations.AlterUniqueTogether(
            name='game_object',
            unique_together={('game', 'object')},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name', 'game_object')},
        ),
    ]
